//! Test support for renderers behind `blackbox-gfx`.
//!
//! Everything here is procedural: meshes, textures and scenes are generated by code, so no game data
//! is needed and any renderer can build the same scenes through the [`RenderBackend`] trait. The crate
//! has no GPU API dependency; it only knows `blackbox-gfx` and `glam`.
//!
//! - [`scenes`]: the synthetic scenes ([`SceneId`]) and how to render one ([`capture_scene`]);
//! - [`metrics`]: image differences (max, mean, p99) with an optional region mask, and the tolerance
//!   classes for comparing two renderers;
//! - [`digest`]: a 32x18 grid of mean colours, small enough to keep as a Rust constant, for catching
//!   unintended changes to one renderer's output;
//! - building blocks the scenes use: [`camera`], [`mesh`], [`texture`], [`bc1`].
//!
//! [`RenderBackend`]: blackbox_gfx::RenderBackend

pub mod bc1;
pub mod camera;
pub mod digest;
pub mod mesh;
pub mod metrics;
pub mod scenes;
pub mod texture;

pub use digest::{Digest, DigestError, DigestReport};
pub use metrics::{CompareError, ImageDiff, Mask, Region, Tolerance, compare};
pub use scenes::{BuiltScene, Fidelity, SceneId, capture_scene};
