[package]
name = "nfsmw-geometry"
description = "Reader for NFS: Most Wanted solids (GeometryPack chunks)."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
nfsmw-bchunk.workspace = true
nfsmw-compress.workspace = true
thiserror.workspace = true

[lints]
workspace = true
