[package]
name = "nfsmw-compress"
description = "EA Black Box compression wrappers used by NFS: Most Wanted (JDLZ, RAWW, HUFF)."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
thiserror.workspace = true

[lints]
workspace = true
