[package]
name = "nfsmw-texture"
description = "Reader for NFS: Most Wanted TPK texture packs, plus CPU pixel decoding."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
nfsmw-bchunk.workspace = true
nfsmw-compress.workspace = true
texture2ddecoder.workspace = true
thiserror.workspace = true

[lints]
workspace = true
