//! Every testkit scene under every setting combination against its recorded digest.
//!
//! Any change to what the native renderer draws moves some digest cell. When the change is intended,
//! regenerate the digests in the same commit (see `docs/testing.md`):
//!
//! ```text
//! BLACKBOX_UPDATE_DIGESTS=1 cargo test -p blackbox-render --lib native_digests -- --include-ignored --nocapture
//! ```
//!
//! That prints the new constants between `//// FILE` and `//// END` marker lines, and writes nothing.

use blackbox_gfx::RenderBackend;
use blackbox_gfx_testkit::{Digest, SceneId, capture_scene};

use super::{SIZE, combos, digests};
use crate::gpu::test_support::{self, Family};

/// How far a digest cell may be from the recorded one, per channel. The digest averages 8x8 pixels, so
/// this is generous for a deterministic GPU and still tight enough to see a changed blend or shader.
const TOLERANCE: u8 = 2;

fn updating() -> bool {
    std::env::var("BLACKBOX_UPDATE_DIGESTS").is_ok_and(|v| !v.is_empty() && v != "0")
}

fn const_name(scene: SceneId) -> String {
    scene.name().to_ascii_uppercase()
}

/// The text of one generated digests file: a constant per scene and the table that lists them.
fn file_text(adapter: &str, driver: &str, combo: &str, digests: &[(SceneId, Digest)]) -> String {
    let mut out = format!(
        "//! Native renderer digests for the `{combo}` settings.\n\
         //! Recorded on {adapter}, Vulkan.\n\
         //! Driver: {driver}.\n\
         //! Generated by `BLACKBOX_UPDATE_DIGESTS=1`; see docs/testing.md. Do not edit by hand.\n\n"
    );
    for (scene, digest) in digests {
        out.push_str(&digest.to_const(&const_name(*scene)));
        out.push('\n');
    }
    out.push_str(&format!("pub const ALL: [(&str, &str); {}] = [\n", digests.len()));
    for (scene, _) in digests {
        out.push_str(&format!("    (\"{}\", {}),\n", scene.name(), const_name(*scene)));
    }
    out.push_str("];\n");
    out
}

#[test]
#[ignore = "needs a GPU"]
fn native_digests_match() {
    let _gpu = test_support::serial();
    let Some(mut renderer) = test_support::headless((SIZE[0], SIZE[1])) else { return };
    let info = renderer.info().clone();
    let Some(family) = Family::of(&info) else {
        eprintln!("skipping: no digests are recorded for {} ({}, {})", info.adapter, info.api, info.driver);
        return;
    };
    let update = updating();
    let mut failures = Vec::new();
    for combo in combos() {
        let resolved = renderer.apply_graphics(&combo.settings);
        assert!(
            resolved.is_exact(),
            "{}: the native renderer runs this as asked: {:?}",
            combo.name,
            resolved.downgrades
        );
        assert_eq!(renderer.draws_directly(), combo.direct, "{}: expected path", combo.name);
        let mut fresh = Vec::new();
        for scene in SceneId::ALL {
            let image = capture_scene(&mut renderer, scene, SIZE).expect("capture");
            let digest = Digest::of(&image).expect("digest");
            if !update {
                let Some(hex) = digests::expected(family, combo.name, scene.name()) else {
                    failures.push(format!("{}/{}: no digest recorded", combo.name, scene.name()));
                    continue;
                };
                let report = digest.compare(&Digest::from_hex(hex).expect("a valid recorded digest"), TOLERANCE);
                if !report.is_within() {
                    failures.push(format!("{}/{}: {report}", combo.name, scene.name()));
                }
            }
            fresh.push((scene, digest));
        }
        if update {
            println!("//// FILE: intel_xe/{}.rs", combo.name);
            print!("{}", file_text(&info.adapter, &info.driver, combo.name, &fresh));
            println!("//// END");
        }
    }
    assert!(
        failures.is_empty(),
        "the native image changed (regenerate with BLACKBOX_UPDATE_DIGESTS=1 if that is intended):\n{}",
        failures.join("\n")
    );
}

#[test]
fn the_recorded_digests_are_well_formed_and_complete() {
    for family in [Family::IntelXeVulkanMesa] {
        for combo in combos() {
            for scene in SceneId::ALL {
                let hex = digests::expected(family, combo.name, scene.name())
                    .unwrap_or_else(|| panic!("{}/{}: no digest recorded", combo.name, scene.name()));
                Digest::from_hex(hex).unwrap_or_else(|e| panic!("{}/{}: {e}", combo.name, scene.name()));
            }
        }
    }
}

#[test]
fn the_digest_text_names_every_scene() {
    let flat = Digest::from_hex(&"808080".repeat(blackbox_gfx_testkit::digest::CELLS)).unwrap();
    let text =
        file_text("Some GPU", "Mesa 1.0", "direct", &[(SceneId::Grid, flat.clone()), (SceneId::AlphaCards, flat)]);
    assert!(text.contains("pub const GRID: &str"));
    assert!(text.contains("pub const ALPHA_CARDS: &str"));
    assert!(text.contains("(\"alpha_cards\", ALPHA_CARDS),"));
    assert!(text.contains("pub const ALL: [(&str, &str); 2]"));
}
